[package]
name = "newpass"
version = "0.1.0"
authors = ["Michael Madden <mikemadden42@icloud.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.9.2"
