[package]
name = "newpass"
version = "0.1.0"
authors = ["Michael Madden <Michael.J.Madden@centene.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.0"
